CREATE TABLE IF NOT EXISTS bookings
(
    id BIGSERIAL PRIMARY KEY,
    buyer_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL
        DEFAULT 'IN_PROGRESS'
        CHECK (status IN ('IN_PROGRESS', 'CONFIRMED', 'EXPIRED', 'CANCELLED')),
    expires_at TIMESTAMP
);