CREATE TABLE IF NOT EXISTS bookings
(
    id BIGSERIAL PRIMARY KEY,
    buyer_email VARCHAR(320) NOT NULL,
    status VARCHAR(20) NOT NULL
        DEFAULT 'IN_PROGRESS'
        CHECK (status IN ('IN_PROGRESS', 'PAYMENT_INITIALIZED', 'PAYMENT_SUCCEEDED', 'EXPIRED', 'CANCELLED')),
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);