server:
  port: 8080

app:
  base-url: ${APP_BASE_URL:http://localhost:${server.port}}
  reservation-period-seconds: ${APP.RESERVATION_PERIOD_SECONDS:900}

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/jticket_bookingdb
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all