spring:
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: '*' #serialization is done by trusted source
      auto-offset-reset: earliest
